name: Increment Major Version on Main

on:
  push:
    branches:
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Increment major version
      run: |
        TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
        NEW_TAG=$(echo $TAG | awk -F. '{OFS="."; $1+=1; $2=0; $3=0; print}')
        echo "Creating new tag $NEW_TAG"
        git tag $NEW_TAG
        git push origin $NEW_TAG