version: '3.4'

services:
  backend:
    build:
      context: ./
      dockerfile: appleEarStore.WebApi/Dockerfile
    ports:
      - "5112:80"
      - "43321:43321"
    environment:
      - "Logging__LogLevel__Default=Information"
      - "Logging__LogLevel__Microsoft.AspNetCore=Warning"
      - "AllowedHosts=*"
      - "ConnectionStrings__BddConnection=$BDD_CONNECTION"
      - "Jwt__SecretKey=$JWT_SECRET_KEY"
      - "Jwt__Issuer=backend"
      - "Jwt__Audience=ecommercefrontend"
      - "Jwt__ExpiresInHours=3"
      - "StripeSettings__ApiKey=$STRIPE_API_KEY"
