name: Increment Minor Version

on:
  pull_request:
    branches:
      - develop
    types: [opened, reopened, synchronize]

jobs:
  run-tests:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.x

      - name: Restore dependencies
        run: dotnet restore "./UnitTest/UnitTest.csproj"

      - name: Test
        run: dotnet test UnitTest/UnitTest.csproj --configuration "$BUILD_CONFIG" --logger "trx;LogFileName=test-results.trx" || true

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: DotNET Tests
          path: "**/test-results.trx"                            
          reporter: dotnet-trx
          fail-on-error: true
  versioning:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Increment major version and push tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
        NEW_TAG=$(echo $TAG | awk -F. '{OFS="."; $2+=1; $3=0; print}')
        echo "Creating new minor tag $NEW_TAG"
        git tag $NEW_TAG
        git push https://${GITHUB_TOKEN}@github.com/erwinGos/e-commerce-modulable.git $NEW_TAG
