name: Increment Major Version on Main

on:
  pull_request:
    branches:
      - develop
    types: [opened, reopened, synchronize]

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Increment major version and push tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
        NEW_TAG=$(echo $TAG | awk -F. '{OFS="."; $2+=1; $3=0; print}')
        echo "Creating new minor tag $NEW_TAG"
        git tag $NEW_TAG
        git push https://${GITHUB_TOKEN}@github.com/erwinGos/e-commerce-modulable.git $NEW_TAG
