name: Increment Major Version

on:
  pull_request:
    branches:
      - develop
    types: [opened, reopened, synchronize]
    
jobs:
  run-tests:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.x

      - name: Restore dependencies
        run: dotnet restore "./UnitTest/UnitTest.csproj"

      - name: Test
        run: dotnet test UnitTest/UnitTest.csproj --configuration "$BUILD_CONFIG" --logger "trx;LogFileName=test-results.trx" || true

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: DotNET Tests
          path: "**/test-results.trx"                            
          reporter: dotnet-trx
          fail-on-error: true
